@BASE_URL = http://localhost:3000


### GET - /
GET {{BASE_URL}}/


### POST - /auth/register
POST {{BASE_URL}}/auth/register
Content-Type: application/json

{
    "name": "Jonson Cave",
    "email": "jonson.cave@ex.com",
    "password": "12345678",
    "role": "DONOR"
}


### POST - /auth/login
POST {{BASE_URL}}/auth/login
Content-Type: application/json

{
    "email": "jonson.cave@ex.com",
    "password": "12345678"
}


### POST - /auth/logout
POST {{BASE_URL}}/auth/logout


### GET - /users/profile
GET {{BASE_URL}}/users/profile


### DELETE - /users/account
DELETE {{BASE_URL}}/users/account


### GET - /donor/profile
GET {{BASE_URL}}/donor/profile


### PATCH - /donor/profile
PATCH {{BASE_URL}}/donor/profile
Content-Type: application/json

{
  "city": "London",
  "address": "221B Baker Street",
  "state": "Greater London",
  "pincode": "110001",
  "lat": 28.6139,
  "lng": 77.2090
}