@BASE_URL = http://localhost:3000


### GET - /
GET {{BASE_URL}}/


### POST - /auth/register
POST {{BASE_URL}}/auth/register
Content-Type: application/json

{
    "name": "Jonson Cave",
    "email": "jonson.cave@ex.com",
    "password": "12345678",
    "role": "DONOR"
}


### POST - /auth/login
POST {{BASE_URL}}/auth/login
Content-Type: application/json

{
    "email": "jonson.cave@ex.com",
    "password": "12345678"
}


### POST - /auth/logout
POST {{BASE_URL}}/auth/logout


### GET - /users/profile
GET {{BASE_URL}}/users/profile


### DELETE - /users/account
DELETE {{BASE_URL}}/users/account


### GET - /donor/profile
GET {{BASE_URL}}/donor/profile


### PATCH - /donor/profile
PATCH {{BASE_URL}}/donor/profile
Content-Type: application/json

{
  "city": "London",
  "address": "221B Baker Street",
  "state": "Greater London",
  "pincode": "110001",
  "lat": 28.6139,
  "lng": 77.2090
}


### POST - /donor/donations
POST {{BASE_URL}}/donor/donations
Content-Type: application/json

{
  "title": "Clothes and Books Donation",
  "description": "Gently used items available for pickup",
  "category": "CLOTHES",
  "pickupAddress": "123 Civil Lines",
  "pickupCity": "Prayagraj",
  "pickupState": "Uttar Pradesh",
  "pickupPincode": "211001",
  "pickupLat": 25.4358,
  "pickupLng": 81.8463,
  "photos": [
    "https://example.com/photo1.jpg",
    "https://example.com/photo2.jpg"
  ],
  "items": [
    {
      "name": "T-Shirts",
      "category": "CLOTHES",
      "quantity": 5,
      "condition": "FAIR"
    },
    {
      "name": "Engineering Books",
      "category": "BOOKS",
      "quantity": 3,
      "condition": "NEW"
    }
  ]
}


### GET - /donor/donations
GET {{BASE_URL}}/donor/donations


### GET - /donor/donations/:donationID
GET {{BASE_URL}}/donor/donations/51eb7798-526a-4e31-afbd-a073b69eea58